# Generated by Django 5.1.3 on 2024-11-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='api_endpoint',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
