# Generated by Django 5.1.3 on 2024-11-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_model_api_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='ip_address',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
